import "./globals.css";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Roboto } from "next/font/google";
import { MainLayout } from "@/ui/main-layout";
import { AuthProvider } from "@/contexts/auth";
import { ThemeProvider } from "@/contexts/theme";
import { Analytics } from "@vercel/analytics/react";

const roboto = Roboto({
  preload: true,
  style: "normal",
  display: "swap",
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) => {
  const isOriginalyDark = cookies().get("app.isDark")?.value === "true";

  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.variable} font-roboto overflow-x-hidden md:w-screen`}
      >
        <ThemeProvider {...{ isOriginalyDark }}>
          <AuthProvider>
            <MainLayout>{children}</MainLayout>
          </AuthProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
};

export default RootLayout;
